name: Car Assembly with Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create build directory and add details
        run: |
          mkdir -p build
          echo "Car Body" > build/car.txt
          echo "Engine" >> build/car.txt
          echo "Wheels" >> build/car.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: car-details  
          path: ./build      

  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: car-details  

      - name: Test car details
        run: |
          if grep -q "Car Body" ./build/car.txt; then
            echo "Car Body is present"
          fi
          if grep -q "Engine" ./build/car.txt; then
            echo "Engine is present"
          fi
          if grep -q "Wheels" ./build/car.txt; then
            echo "Wheels are present"
          fi