name: Car Assembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Create build directory
        run: mkdir -p build

      - name: Add car parts to build file
        run: |
          cd build
          echo "Body" >> car_parts.txt
          echo "Engine" >> car_parts.txt
          echo "Wheels" >> car_parts.txt
          echo "Doors" >> car_parts.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: car-parts
          path: build/car_parts.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: car-parts

      - name: Check if car parts are in the file
        run: |
          cd build
          grep -q "Body" car_parts.txt
          grep -q "Engine" car_parts.txt
          grep -q "Wheels" car_parts.txt
          grep -q "Doors" car_parts.txt
