name: Car Assembly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create build folder and add car parts
      run: |
        mkdir build
        echo "Body" > build/car_parts.txt
        echo "Engine" >> build/car_parts.txt
        echo "Wheels" >> build/car_parts.txt
        echo "Doors" >> build/car_parts.txt
        echo "Windows" >> build/car_parts.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: car-build
        path: build/
        
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: car-build

    - name: Test car parts presence
      run: |
        if grep -q "Body" build/car_parts.txt && \
           grep -q "Engine" build/car_parts.txt && \
           grep -q "Wheels" build/car_parts.txt && \
           grep -q "Doors" build/car_parts.txt && \
           grep -q "Windows" build/car_parts.txt; then
            echo "All car parts are present"
        else
            echo "Some car parts are missing"
            exit 1
        fi
